### ISSUE TITLE
startRecording() crashing 

### ISSUE THREAD

**Issue by svm1** [simonbromberg/SBSpeechRecognizer#2]
Hi there,

Been using your framework for a while and it's been really solid! Just recently been running into a small issue - when I call the startRecording() function, it suddenly crashes at this point:

`let inputNode = audioEngine.inputNode`
(line 83 of SBSpeechRecognizer.swift)

This doesn't always happen, and I am not sure why it is happening. Weirdest part is this hasn't always happened (only started recently) but I haven't changed anything related to the audio component since I initially implemented your framework a couple months ago. Even now, it only happens randomly and occasionally (ironically making it a bit scarier!)

Do you have any suggestions as to what I should look into or what may be causing this? I would provide more error log info, but all Xcode is giving me is a list of memory addresses which doesn't seem to be very helpful.

**Comment by simonbromberg** [comment]
What does the crash say?

**Comment by svm1** [comment]
`libc++abi.dylib__cxa_throw:`

`->  0x10b6b6acc <+0>:   pushq  %rbp`


    0x10b6b6acd <+1>:   movq   %rsp, %rbp
    0x10b6b6ad0 <+4>:   pushq  %r15
    0x10b6b6ad2 <+6>:   pushq  %r14
    0x10b6b6ad4 <+8>:   pushq  %r12
    0x10b6b6ad6 <+10>:  pushq  %rbx
    0x10b6b6ad7 <+11>:  movq   %rdx, %r14
    0x10b6b6ada <+14>:  movq   %rsi, %r15
    0x10b6b6add <+17>:  movq   %rdi, %rbx
    0x10b6b6ae0 <+20>:  callq  0x10b6b6924               ; __cxa_get_globals
    0x10b6b6ae5 <+25>:  movq   %rax, %r12
    0x10b6b6ae8 <+28>:  callq  0x10b6b7060               ; std::get_unexpected()
    0x10b6b6aed <+33>:  movq   %rax, -0x60(%rbx)
    0x10b6b6af1 <+37>:  callq  0x10b6b7098               ; std::get_terminate()
    0x10b6b6af6 <+42>:  movq   %rax, -0x58(%rbx)
    0x10b6b6afa <+46>:  movq   %r15, -0x70(%rbx)
    0x10b6b6afe <+50>:  movq   %r14, -0x68(%rbx)
    0x10b6b6b02 <+54>:  leaq   -0x20(%rbx), %r14
    0x10b6b6b06 <+58>:  movabsq $0x434c4e47432b2b00, %rax ; imm = 0x434C4E47432B2B00 
    0x10b6b6b10 <+68>:  movq   %rax, -0x20(%rbx)
    0x10b6b6b14 <+72>:  movq   $0x1, -0x78(%rbx)
    0x10b6b6b1c <+80>:  incl   0x8(%r12)
    0x10b6b6b21 <+85>:  leaq   0x1d(%rip), %rax          ; __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
    0x10b6b6b28 <+92>:  movq   %rax, -0x18(%rbx)
    0x10b6b6b2c <+96>:  movq   %r14, %rdi
    0x10b6b6b2f <+99>:  callq  0x10b6b960c               ; symbol stub for: _Unwind_RaiseException
    0x10b6b6b34 <+104>: movq   %r14, %rdi
    0x10b6b6b37 <+107>: callq  0x10b6b6b68               ; __cxa_begin_catch
    0x10b6b6b3c <+112>: movq   -0x58(%rbx), %rdi
    0x10b6b6b40 <+116>: callq  0x10b6b70a6               ; std::__terminate(void (*)())

**Comment by svm1** [comment]
<img width="264" alt="screen shot 2018-09-06 at 3 32 07 pm" src="https://user-images.githubusercontent.com/9904305/45188636-1bb35000-b1ea-11e8-9c0b-9b0bb489a0c9.png">
<img width="1130" alt="screen shot 2018-09-06 at 3 32 25 pm" src="https://user-images.githubusercontent.com/9904305/45188644-21a93100-b1ea-11e8-97d5-36d4a70f1d44.png">

**Comment by svm1** [comment]
@simonbromberg 

I added the error log as well as screenshots of the stack trace and line that caused the crash, hope these help. Please let me know if there's anything else I can provide. 

I did more testing and realize that this crash only happens when I run the app from Xcode, whether I use a physical device or emulator. If I run the app independently of Xcode (running it without being connected to the Xcode debugger), then it never crashes and the speech functionality works perfectly. Only when I launch the app from Xcode do I see this scenario with this crash.

**Comment by svm1** [comment]
So I followed the advice in [this thread](https://stackoverflow.com/questions/29003302/avaudioengine-inputnode-call-throws-error) - I removed the breakpoints as suggested and it solved the problem. I don't really understand what was happening, but it doesn't seem like an issue with your framework, especially considering when and how it manifested.
